# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "colorize", "~> 0.8.1"

gem "tty", "~> 0.7.0"

gem "artii", "~> 2.1"

gem "rubocop", "~> 0.59.2"

gem "rainbow", "~> 3.0"
